### ISSUE TITLE
Large Model - GPipe Transformer - OOM Issue

### ISSUE THREAD

**Issue by msharmavikram** [tensorflow/lingvo#100]
I am trying to run the large model described in the comment section of  https://github.com/tensorflow/lingvo/blob/master/lingvo/tasks/lm/params/one_billion_wds.py#L179 

However, I keep getting OOM error.

Following are the variations I have tried: 
#4 GPU mode:
SPLITS = [2 + 11 * i for i in range(GPU-1)]
LAYERS = SPLIT[-1]
BATCH = 2 or 4 or 8
MICROBATCH =2 or 4 or 8 (respectively) 

#8 GPU mode :
EMBEDDING_DIM = 1024
GPUS = 8  # For example, on 8 accelerator, each of which has 16G mem.
SPLITS = [10 + 12 * i for i in range(GPUS - 1)]
LAYERS = SPLITS[-1]  #4.9B params
BATCH_SIZE = 2
NUM_MICRO_BATCHES = 2

```
...
019-06-08 01:46:36.299559: I tensorflow/core/common_runtime/bfc_allocator.cc:824] Stats:
Limit:                 15750955008
InUse:                 15584222976
MaxInUse:              15584223232
NumAllocs:                    2361
MaxAllocSize:           3250061312

2019-06-08 01:46:36.299616: W tensorflow/core/common_runtime/bfc_allocator.cc:319] ****************************************************************************************************
2019-06-08 01:46:36.299642: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at matmul_op.cc:480 : Resource exhausted: OOM when allocating tensor with shape[169,793472] and type float on /job:local/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2019-06-08 01:46:36.919956: I lingvo/core/ops/record_yielder.cc:317] 0x7fa6a682e060Basic record yielder exit
I0608 01:46:41.227104 140355034937088 base_runner.py:239] trainer done (fatal error).
I0608 01:46:41.227474 140355034937088 base_runner.py:118] trainer exception: From /job:local/replica:0/task:0:
[_Derived_]OOM when allocating tensor with shape[1024,49592] and type float on /job:local/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node Add_28}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[gradients/fprop/1bwds_wpm_level_lm/tower_0_0/Sum_435_grad/Tile_G4412]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


E0608 01:46:41.230962 140355034937088 base_runner.py:246] Traceback (most recent call last):
E0608 01:46:41.231157 140355034937088 base_runner.py:246]   File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/base_runner.py", line 199, in _RunLoop
E0608 01:46:41.231286 140355034937088 base_runner.py:246]     loop_func(*loop_args)
E0608 01:46:41.231404 140355034937088 base_runner.py:246]   File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 538, in _Loop
E0608 01:46:41.231527 140355034937088 base_runner.py:246]     model_task.per_example_tensors,
E0608 01:46:41.231688 140355034937088 base_runner.py:246]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 950, in run
E0608 01:46:41.231817 140355034937088 base_runner.py:246]     run_metadata_ptr)
E0608 01:46:41.231914 140355034937088 base_runner.py:246]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
E0608 01:46:41.231992 140355034937088 base_runner.py:246]     feed_dict_tensor, options, run_metadata)
E0608 01:46:41.232054 140355034937088 base_runner.py:246]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
E0608 01:46:41.232116 140355034937088 base_runner.py:246]     run_metadata)
E0608 01:46:41.232177 140355034937088 base_runner.py:246]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
E0608 01:46:41.232239 140355034937088 base_runner.py:246]     raise type(e)(node_def, op, message)
E0608 01:46:41.232300 140355034937088 base_runner.py:246] ResourceExhaustedError: From /job:local/replica:0/task:0:
E0608 01:46:41.232366 140355034937088 base_runner.py:246] [_Derived_]OOM when allocating tensor with shape[1024,49592] and type float on /job:local/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
E0608 01:46:41.232431 140355034937088 base_runner.py:246]        [[{{node Add_28}}]]
E0608 01:46:41.232492 140355034937088 base_runner.py:246] Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
E0608 01:46:41.232563 140355034937088 base_runner.py:246]
E0608 01:46:41.232625 140355034937088 base_runner.py:246]        [[gradients/fprop/1bwds_wpm_level_lm/tower_0_0/Sum_435_grad/Tile_G4412]]
E0608 01:46:41.232690 140355034937088 base_runner.py:246] Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
E0608 01:46:41.232752 140355034937088 base_runner.py:246]
E0608 01:46:41.232812 140355034937088 base_runner.py:246]
```

**Comment by bignamehyp** [comment]
Maybe use a wordpiece model to reduce the vocab size? What gpu did you use? We will update transformer examples tested on 8 V100s.

**Comment by msharmavikram** [comment]
I am using V100 - 16GB version. 

I switched to V100-32GB version later today. I was able to run for a longer number of steps - say 600 odd. But eventually, I end up getting this error. I suspect if there is some other issue. I don't understand why the memory size grows with the step size.

Adding one more observation:

Increasing the batch size, keeping all the dims sizes as constant and GPU = 8, the OOM error occurs earlier. 

Batch Size | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128
-- | -- | -- | -- | -- | -- | -- | -- | --
number of steps before OOM error  | 462 | 498 | 477 | 466 | 429 | 402 | 381 | 365

**Comment by jonathanasdf** [comment]
Can you try following the Hint and add "report_tensor_allocations_upon_oom"?

**Comment by msharmavikram** [comment]
I added run_options to https://github.com/tensorflow/lingvo/blob/master/lingvo/trainer.py#L551 sess.run() call. I did not see any difference in the output. Is this the location where I should add or somewhere else @jonathanasdf ?

**Comment by jonathanasdf** [comment]
That should be the right call based on the stack trace. You did

`sess.run(..., options=config_pb2.RunOptions(report_tensor_allocations_upon_oom=True))`

?

**Comment by msharmavikram** [comment]
That is correct. I had tried it with a large batch to see if get anything reasonable error quickly. Let me try with Batch size of 1 and post the log file here. (simple configuration)

**Comment by bignamehyp** [comment]
Updated vocab_size and hyperparamters that were tested on multiple 16GB V100s.

**Comment by msharmavikram** [comment]
I will check the results with the updated codebase. 
Quick question on the comments: 

``` Example large transformer model using GPIPE.
# Relative throughput on multiple V100s, each with 16GB ram.
# GPUs throughput
# 1    1
# 2    0.93
# 4    0.85
# 8    0.775
```
This is keeping the number of layers constant (keeping work constant or strong scaling right?)

**Comment by msharmavikram** [comment]
I did a fresh clone of the repo and used the updated configuration on a single GPU - V100 - 32 GB system. I reduced the batch size to 2 to so that i dont get any errors. However, I still ended up getting OOM error. I have enabled the hints this time in trainer.py and have attached the log here. 

[run_upload.log](https://github.com/tensorflow/lingvo/files/3288070/run_upload.log)


Let me know if I am doing something wrong. Thanks!

**Comment by bignamehyp** [comment]
To answer your previous question, we keep the number of layers in each device constant.  So the more gpus, the larger the model is. 

# GPUs layers throughput
# 1     8    1
# 2    16    0.93
# 4    24    0.85
# 8    32    0.775


From the logs it showed:

Sum Total of in-use chunks: 4.08GiB

2019-06-13 20:33:50.415928: I tensorflow/core/common_runtime/bfc_allocator.cc:818] total_region_allocated_bytes_: 4384489472 memory_limit_: 4384489472 available bytes: 0 curr_region_allocation_bytes_: 8768978944

2019-06-13 20:33:50.415937: I tensorflow/core/common_runtime/bfc_allocator.cc:824] Stats: 
Limit:                  4384489472
InUse:                  4384304896
MaxInUse:               4384308736
NumAllocs:                     689
MaxAllocSize:            262144000

It seemed the gpus have been occupied.
Maybe run nvidia-smi to find out which programs were in use.

**Comment by msharmavikram** [comment]
Thanks for the details and you are right, there was a conflict of task happening. Thanks for pointing it out (I did not pay attention to it)!
