### ISSUE TITLE
can we run pre-trained model?

### ISSUE THREAD

**Issue by m3m3-chan** [tensorflow/lingvo#101]
Hello, 
nice project! I read the home page but I couldn't confirm if the code provides usage of pretrained model for speech to text or we have to train ours?
can you please give more explanation on what this code does?

Regards,

**Comment by jonathanasdf** [comment]
Currently no pretrained models are available. It's not clear if we will release them in the future. If we do we will try to make sure they are linked in the section https://github.com/tensorflow/lingvo#current-models
