### ISSUE TITLE
Enhancement Request: Auto detect number of GPUs  

### ISSUE THREAD

**Issue by msharmavikram** [tensorflow/lingvo#102]
For running GPipe implementation, currently, the users have to specify the number of GPUs every time when he makes a change as shown here: https://github.com/tensorflow/lingvo/blob/master/lingvo/tasks/lm/params/one_billion_wds.py#L195

It would be great if it could auto-detect the number GPUs. This would help when running batch jobs and doing scaling efficiency measurements.

**Comment by drpngx** [comment]
You can use `list_local_devices`.
https://stackoverflow.com/questions/38559755/how-to-get-current-available-gpus-in-tensorflow

Please bear in mind that the batch size might be different, and batch size
might affect other parameters, so two experiments with the same
configuration might not return the same result which could be confusing.

Patrick
