### ISSUE TITLE
Is the ASR task only capable of handling 16KHz single channel audio? Can I train it with multi-channel audios at other frequencies?

### ISSUE THREAD

**Issue by iamxiaoyubei** [tensorflow/lingvo#104]
I found that the ASR task can't handle multi-channel audio, and it doesn't predict well on other frequencies.(which trained on librispeech datasets with 16KHz mono audios)

So, is the ASR task only capable of handling 16KHz single channel audio? Can I train it with multi-channel audios at other frequencies?

Thank you!

**Comment by rprabhavalkar** [comment]
Yes, you're right that the the code currently assumes single-channel 16kHZ audio input in multiple places (e.g., frame extraction from audio, the input_generator, etc). 
https://github.com/tensorflow/lingvo/blob/master/lingvo/tasks/asr/frontend.py#L207

If you'd like to train it with other sampling rates, you would need to modify the input processing code. As long as you can create data with the correct input shapes, all of the changes will likely be restricted to the feature processing (i.e., you probably don't need many changes in the encoder/decoder code).

**Comment by iamxiaoyubei** [comment]
Ok, I understand. Thank you~!

Can you please help me have a look at this problem? #103

**Comment by zh794390558** [comment]
watch this.
