### ISSUE TITLE
How to use Bazel build target with python3

### ISSUE THREAD

**Issue by EmpRamses** [tensorflow/lingvo#113]
I've noticed that Lingvo codes support both python2 and python3. But when I use Bazel to build these targets, it seems that Bazel try to use python2 as default. How can I configure the Bazel to use python3 as default?

**Comment by drpngx** [comment]
Maybe a recent version has this?
https://github.com/emusand/bazel/commit/6190cfc3a5be3fefc40b055fc2e68b8aee2b5cd1

**Comment by EmpRamses** [comment]
@drpngx Thank you. I got it. Maybe I asked a wrong question. I found that the Bazel only recognize the command "python" instead of "python3". I have no idea how to make Bazel use the command "python3". So I just build a soft link from "python3" to "python". And it worked.

**Comment by oplatek** [comment]
@EmpRamses I am a very new to Bazel build system, can you pls share how did you do it exactly?

I used conda environment while building lingvo. In this conda environment `which python` defaults to python3.6 but bazel build the targets with python2.7 which is otherwise the system-wide default python.

**Comment by jonathanasdf** [comment]
bazel python2/python3 support seems to be in flux right now, but hopefully it should resolve soon and should default to python3 by end of year.

By the way, we now have a pip package so you should be able to pip[3] install lingvo and avoid everything to do with bazel.
https://pypi.org/project/lingvo

We're still in the progress of updating our docs though.

**Comment by drpngx** [comment]
Awesome!

**Comment by EmpRamses** [comment]
@oplatek I've done my project with lingvo for a long time. And I cannot remember how I did it. But I just found a Dockerfile on my server. Maybe it can help you.

[dev3.dockerfile.txt](https://github.com/tensorflow/lingvo/files/3628910/dev3.dockerfile.txt)
ps. It's actually a dockerfile rather than a txt. I change it to txt just for upload to this comment.

**Comment by oplatek** [comment]
Thank you @EmpRamses !
