### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by fanlu** [tensorflow/lingvo#13]
hi, @drpngx , the fraction_of_correct_next_step_preds will decrease to zero at step 20k, Is this behavior strange?
![image](https://user-images.githubusercontent.com/1620875/49487003-8fadd480-f87b-11e8-88b7-fa75d803d08b.png)
![image](https://user-images.githubusercontent.com/1620875/49487029-af44fd00-f87b-11e8-90e2-2bcab42623ac.png)
![image](https://user-images.githubusercontent.com/1620875/49487037-ba982880-f87b-11e8-8f56-07d3ba0a02c8.png)

**Comment by drpngx** [comment]
Yes, that's very strange. Are you doing training on multi-machines? Did you abort the job and restart at some point? Could you zip up the tfevents files and upload them to a place where we can download them?

**Comment by fanlu** [comment]
this is the command I used in local machine and sync mode.
```
bazel-bin/lingvo/trainer --run_locally=gpu --mode=sync --model=asr.librispeech.Librispeech960Grapheme --logdir=/tmp/librispeech/log --logtostderr --enable_asserts=false
```
zip tfevents may takes a lot of time. I will upload it to dropbox when it finished.

**Comment by drpngx** [comment]
Oh sorry, it's the variational [noise](https://github.com/tensorflow/lingvo/blob/master/lingvo/tasks/asr/params/librispeech.py#L175). If you turn that off it'll be `0.1%` to `0.2%` worse. I think it's probably because we used more machines so the variance might have to be tuned.

**Comment by fanlu** [comment]
OK, I'll try it. I have another question, How much time will 853.2K steps and 632.6K steps cost on this two different models?
```
  """Base params for Librispeech 960 hour experiments using grapheme models.

  With 8 workers using asynchronous gradient descent on 16 (8x2) GPUs, the model
  achieves the following error rates after ~853.2K steps:
    Dev:        5.2%
    DevOther:  15.2%
    Test:       5.4%
    TestOther: 15.5%
  """
 """Base params for Librispeech 960 hour experiments using Word Piece Models.

  With 8 workers using asynchronous gradient descent on 16 (8x2) GPUs, the model
  achieves the following error rates after ~632.6K steps:
    Dev:        4.3%
    DevOther:  13.0%
    Test:       4.5%
    TestOther: 13.2%
  """
```

**Comment by drpngx** [comment]
The grapheme ran for about 11 days and the wpm ran for about 9 days. You
can look at the "global_step" scalar on tensorboard to see how many steps
per second it runs.

**Comment by caosongjun** [comment]
> hi, @drpngx , the fraction_of_correct_next_step_preds will decrease to zero at step 20k, Is this behavior strange?
> ![image](https://user-images.githubusercontent.com/1620875/49487003-8fadd480-f87b-11e8-88b7-fa75d803d08b.png)
> ![image](https://user-images.githubusercontent.com/1620875/49487029-af44fd00-f87b-11e8-90e2-2bcab42623ac.png)
> ![image](https://user-images.githubusercontent.com/1620875/49487037-ba982880-f87b-11e8-8f56-07d3ba0a02c8.png)

I have the same problem. Is it due to the variational noise mentioned above?

**Comment by drpngx** [comment]
Yes it's the variational noise. Usually it tends to recover a bit faster. It could be due to a different training configuration. Try to reducing the variance `p.train.vn_std`.

**Comment by YuMS** [comment]
> Oh sorry, it's the variational [noise](https://github.com/tensorflow/lingvo/blob/master/lingvo/tasks/asr/params/librispeech.py#L175). If you turn that off it'll be `0.1%` to `0.2%` worse. I think it's probably because we used more machines so the variance might have to be tuned.

Hi Dr. Nguyen @drpngx , I found switching on and off `p.vn.global_vn` makes a much bigger difference than you mentioned(1.2% vs 0.2%). **Is there something I might have done wrong?**
The table below shows our result:

global_vn | dev_clean | dev_other | test_clean | test_other
 -- | -- | -- | -- | --
False | 0.056 | 0.163 | 0.059 | 0.170
True | 0.043 | 0.131 | 0.047 | 0.134

Model: `Librispeech960Wpm`
Step: 140k
commit: `bc33eaf50aa274827beed1c567cb37210e697585`

Diff in `librispeech.py`: 

    > p.vn.global_vn = True
    < p.vn.global_vn = False
