### ISSUE TITLE
Query: Does lingvo-GPIPE support XLA?

### ISSUE THREAD

**Issue by msharmavikram** [tensorflow/lingvo#139]
I am exploring if to use XLA (https://www.tensorflow.org/xla) with pipeline parallelism. I wonder if that would work or if there are any inherent deficiencies in the implementation that I need to be aware of.

**Comment by jonathanasdf** [comment]
@bignamehyp do you know?

**Comment by bignamehyp** [comment]
Yes, it supports XLA.

**Comment by msharmavikram** [comment]
How does the XLA perform layer fusion with pipelining? Especially the graphs that each device work will be different. So, is layer fusion efficient?

**Comment by bignamehyp** [comment]
Sorry I'm not familiar with XLA layer fusion.
