### ISSUE TITLE
How to get all variable names from params?

### ISSUE THREAD

**Issue by by2101** [tensorflow/lingvo#142]
Dear all,
I would like to load ckpt with params.train.init_from_checkpoint_rules. However, when I write loading rules, I found that it is difficult to get all variable names in _Params() function. Because the variables do not exist that time, I can't use tf.get_all_variables() or something. 

So, how to write rules elegantly?

Thank you!

**Comment by jonathanasdf** [comment]
Run training until you get the first checkpoint, then run tensorflow's inspect_checkpoint script.
