### ISSUE TITLE
Why 'contrib cudnn' is removed?

### ISSUE THREAD

**Issue by NiHaoUCAS** [tensorflow/lingvo#156]
https://github.com/tensorflow/lingvo/commit/3721e98913d388043882c6a431f8a3cb0cf2e97a#diff-e7d35ddb38bd70610e4f34f35d47882a
The commit 'Remove contrib cudnn in lingvo.'， as I know, cudnn is much faster then No cudnn, why this feature removed?

**Comment by jonathanasdf** [comment]
tf.contrib (and thus cudnn support) is removed in tf2.0, and we have to remove this dependency to support the upgrade to tf2.0 soon. Unless someone ports the cudnn code and provides a pip package for installing it, there's no way for us to support it after the official migration to tf2.0. See the decision from tf team here: https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md

There is a chance we may support using Keras layers inside Lingvo, and get cudnn support back that way, but there is no current plan or timeline for that. I'm sorry for the inconvenience.

**Comment by NiHaoUCAS** [comment]
> tf.contrib (and thus cudnn support) is removed in tf2.0, and we have to remove this dependency to support the upgrade to tf2.0 soon. Unless someone ports the cudnn code and provides a pip package for installing it, there's no way for us to support it after the official migration to tf2.0. See the decision from tf team here: https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
> 
> There is a chance we may support using Keras layers inside Lingvo, and get cudnn support back that way, but there is no current plan or timeline for that. I'm sorry for the inconvenience.

Thank you for your reply and powerful LINGVO.
