### ISSUE TITLE
ERROR: The 'build' command is only supported from within a workspace.

### ISSUE THREAD

**Issue by zhangdong1992** [tensorflow/lingvo#157]
When I run this command "bazel test -c opt --test_output=streamed //lingvo:trainer_test //lingvo:models_test"  I made an error  The 'build' command is only supported from within a workspace.

How to solve this problem?

**Comment by jonathanasdf** [comment]
Are you running from docker? If you ls do you see any files? If not you probably forgot to set LINGVO_DIR before the docker run command.

**Comment by zhangdong1992** [comment]
oh, I forgot to set LINGVO_DIR. I solved this. thanks
