### ISSUE TITLE
Has anyone ever run an audio adversarial attack against lingvo proposed on ICLR2019?

### ISSUE THREAD

**Issue by zhangdong1992** [tensorflow/lingvo#162]
This paper "Imperceptible, Robust and Targeted Adversarial Examples for Automatic Speech Recognition" proposes an adversarial attack on the lingvoASR system. I followed the method in this link “https://github.com/yaq007/lingvo” and it went wrong. 
I can't compile lingvo using the docker method due to my network problem. Instead, I use bazel directly to compile lingvo,  and there was no error during compilation. But when I was running the code generate_imperceptible_adv.py, I got an error. "process finished with exit code 139 (interrupted by signal 11: SIGSEGV)". This problem has been bothering me for a long time. Does anyone know how to solve it?

**Comment by jonathanasdf** [comment]
If the segfault is from lingvo side, a likely reason is g++ compiler version mismatch. The latest lingvo requires g++7

**Comment by zhangdong1992** [comment]
> If the segfault is from lingvo side, a likely reason is g++ compiler version mismatch. The latest lingvo requires g++7

hi,  @jonathanasdf  I followed your advice.And I found the g++ compiler version mismatch. This code  “https://github.com/yaq007/lingvo” requiers g++ 4.8. But when I switched the gcc version to 4.8.5, I got a new error.
hp@hp:~/lingvo$ bazel build -c opt --config=cuda //lingvo:trainer
Starting local Bazel server and connecting to it...
INFO: Analysed target //lingvo:trainer (35 packages loaded).
INFO: Found 1 target...
ERROR: /home/hp/lingvo/lingvo/core/ops/BUILD:67:1: undeclared inclusion(s) in rule '//lingvo/core/ops:ascii_tokenizer':
this rule is missing dependency declarations for the following files included by 'lingvo/core/ops/ascii_tokenizer.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/x86intrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/ia32intrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/mmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/xmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/mm_malloc.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/emmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/immintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/fxsrintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include/adxintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/limits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/syslimits.h'
Target //lingvo:trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 16.536s, Critical Path: 13.07s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

The environment Configuration I use is as follows
ubuntu 16.04  CUDA Version 10.0.130  cudnn 7.5.1 tensorflow-gpu 1.13.1 bazel 0.17.2

**Comment by jonathanasdf** [comment]
https://stackoverflow.com/questions/53527134/bazel-missing-dependency-declarations-for-stddef-h-and-others-ubuntu-18-04 says a reinstall worked... that's a weird error though

**Comment by zhangdong1992** [comment]
> https://stackoverflow.com/questions/53527134/bazel-missing-dependency-declarations-for-stddef-h-and-others-ubuntu-18-04 says a reinstall worked... that's a weird error though

I solved this error. Thanks!
