### ISSUE TITLE
Comparison between tf1.4 and tf2 on Lingvo 

### ISSUE THREAD

**Issue by NiHaoUCAS** [tensorflow/lingvo#164]
I am using an old version Lingvo(tf1.4), do we have comparison between tf1.4 and tf2.0 on Lingvo for training speed and GPU memory usage?  Thank you!

**Comment by jonathanasdf** [comment]
Sorry, we do not have such benchmarks. But we do not expect any major changes in performance for lingvo, as under the hood we are still using tf.compat.v1 everywhere and have not migrated to using actual tf2 features yet.
