### ISSUE TITLE
saver_max_to_keep not work as setting.

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/lingvo#166]
I set saver_max_to_keep=10, but the ckpt is will grow more than 10, how to fix this ?

**Comment by jonathanasdf** [comment]
Based on https://www.tensorflow.org/api_docs/python/tf/train/CheckpointManager#__init__, it seems checkpoints under keep_checkpoint_every_n_hours are excluded from the max_to_keep limit.

Do you have saver_keep_checkpoint_every_n_hours set to None? Try printing the args in https://github.com/tensorflow/lingvo/blob/7f52ca908c8e3dde5b697f4210c7c5cacc45aa89/lingvo/core/checkpointer.py#L78

If all the args seem to be reasonable values then consider filing a bug with tensorflow.

**Comment by zh794390558** [comment]
I see, thx.
