### ISSUE TITLE
pip3 whl file not being created. error in 1 test case

### ISSUE THREAD

**Issue by smdshakeelhassan** [tensorflow/lingvo#184]
When I am trying to build a pip3 whl file according to the instructions given in pip_package/README.md there are 64 tests that happen but only 63 of them pass. 1 of them viz. hyperparams_test.py fails. When I checked the hyperparams.py source code i see this import "from lingvo.core import hyperparams_pb2" but in lingvo.core no such file exists. Is it a mistake or is it some kind of auto-generated file?

**Comment by argideritzalpea** [comment]
@smdshakeelhassan Do you remember the resolution of this error?

**Comment by KSY22ksy** [comment]
so how to deal with it
