### ISSUE TITLE
Speedup with multiple gpus on same machine

### ISSUE THREAD

**Issue by manish-kumar-garg** [tensorflow/lingvo#192]
When using single gpu:
`Steps/second: 0.129491, Examples/second: 14.229674`

When using `worker_gpus=3 ` on the same machine
`Steps/second: 0.131452, Examples/second: 20.201630`

There is no significant improvement in `steps/second`.
Is this expected?

**Comment by jonathanasdf** [comment]
It is possible your pipeline has a bottleneck in input pipeline, for example disk speed or cpu preprocessing speed.
