### ISSUE TITLE
the difference of `ComputePredictionsDynamic ` and `ComputePredictionsFunctional `

### ISSUE THREAD

**Issue by NiHaoUCAS** [tensorflow/lingvo#196]
There are two ways to compute prediction in asr part(lingvo/tasks/asr/deocoder.py): `ComputePredictionsDynamic ` and `ComputePredictionsFunctional `.  I want to know the difference of the two ways.  The second way seems much faster, but i don't know why. 
 3Q

**Comment by jonathanasdf** [comment]
Dynamic uses tf.compat.v1.while_loop, which is known to be not so efficient. It preallocates output buffers and writes to specific indices each step.
Function uses recurrent.Recurrent, which compiles the loop body into a single function node and is much more efficient. The outputs of each timestep are stacked at the end. But this uses more custom code.
Probably a switch to tf2 while would gain the benefits of both sides. We are currently figuring this out.

**Comment by NiHaoUCAS** [comment]
> Dynamic uses tf.compat.v1.while_loop, which is known to be not so efficient. It preallocates output buffers and writes to specific indices each step.
> Function uses recurrent.Recurrent, which compiles the loop body into a single function node and is much more efficient. The outputs of each timestep are stacked at the end. But this uses more custom code.
> Probably a switch to tf2 while would gain the benefits of both sides. We are currently figuring this out.

thank you for you reply!
