### ISSUE TITLE
Using tf-nightly-gpu==1.13.0.dev2018121  in CUDA9 cannot be installed

### ISSUE THREAD

**Issue by u4lr451** [tensorflow/lingvo#20]
dev.dockerfile descript:
![image](https://user-images.githubusercontent.com/18026245/53395987-45ea0b80-39de-11e9-9d4b-95ecd3aca354.png)

but it's no work:
![image](https://user-images.githubusercontent.com/18026245/53395940-20f59880-39de-11e9-9e2c-d116ae5c7481.png)

**Comment by jonathanasdf** [comment]
Sorry, it looks like the package is no longer available on PyPI. It is an unfortunate limitation that we need to depend on tf-nightly-gpu until the next stable TensorFlow release. For now, your options are to upgrade your nvidia drivers to 410.xx or compile and install TensorFlow from source.
