### ISSUE TITLE
hyperparams_pb2 error

### ISSUE THREAD

**Issue by argideritzalpea** [tensorflow/lingvo#204]
I am attempting to run `lingvo/tasks/asr/tools/librispeech_get_data.sh`
from a build from source within the development docker container.

However, I receive the following error:
```Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/lingvo/lingvo/tools/create_asr_features.py", line 27, in <module>
    from lingvo.tools import audio_lib
  File "/tmp/lingvo/lingvo/tools/audio_lib.py", line 24, in <module>
    from lingvo.core import py_utils
  File "/tmp/lingvo/lingvo/core/py_utils.py", line 35, in <module>
    from lingvo.core import hyperparams
  File "/tmp/lingvo/lingvo/core/hyperparams.py", line 31, in <module>
    from lingvo.core import hyperparams_pb2
ImportError: cannot import name 'hyperparams_pb2'
```

This might be similar to this issue:
https://github.com/tensorflow/lingvo/issues/184

Does anyone know where `hyperparams_pb2` is?

**Comment by argideritzalpea** [comment]
Looks like this needs to be run first: `docs/generate_apidoc.sh`

**Comment by yinjunbo** [comment]
@argideritzalpea Hi, I met the same problem of `cannot import name 'hyperparams_pb2'`. But when I run `docs/generate_apidoc.sh`, another problem happens:
`WARNING: autodoc: failed to import module 'x_ops' from module 'lingvo.core.ops'; the following exception was raised:
dynamic module does not define module export function (PyInit_x_ops)
/home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:21: WARNING: Unexpected indentation.
/home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:39: WARNING: Unexpected indentation.
/home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:57: WARNING: Unexpected indentation.
/home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:62: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.apply_packing:23: WARNING: Unexpected indentation.
/home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:22: WARNING: Unexpected indentation.
/home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:24: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:42: WARNING: Unexpected indentation.
/home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:44: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/ssd/junbo/repository/lingvo/lingvo/tasks/car/ops/__init__.py:docstring of lingvo.tasks.car.ops.average_precision3d:35: WARNING: Unexpected indentation.
WARNING: autodoc: failed to import module 'car_ops' from module 'lingvo.tasks.car.ops'; the following exception was raised:
dynamic module does not define module export function (PyInit_car_ops)`
Do you have an idea for it? Thank you.

**Comment by yinjunbo** [comment]
@argideritzalpea Hi, I met the same problem of cannot import name 'hyperparams_pb2'. But when I run `docs/generate_apidoc.sh`, another problem happens:
```
WARNING: autodoc: failed to import module 'x_ops' from module 'lingvo.core.ops'; the following exception was raised: dynamic module does not define module export function (PyInit_x_ops) /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:21: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:39: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:57: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:62: WARNING: Block quote ends without a blank line; unexpected unindent. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.apply_packing:23: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:22: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:24: WARNING: Block quote ends without a blank line; unexpected unindent. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:42: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:44: WARNING: Block quote ends without a blank line; unexpected unindent. /home/ssd/junbo/repository/lingvo/lingvo/tasks/car/ops/__init__.py:docstring of lingvo.tasks.car.ops.average_precision3d:35: WARNING: Unexpected indentation. WARNING: autodoc: failed to import module 'car_ops' from module 'lingvo.tasks.car.ops'; the following exception was raised: dynamic module does not define module export function (PyInit_car_ops)```

Do you have an idea for it? Thank you.

**Comment by yinjunbo** [comment]
@argideritzalpea Hi, I met the same problem of cannot import name 'hyperparams_pb2'. But when I run `docs/generate_apidoc.sh`, another problem happens:

```WARNING: autodoc: failed to import module 'x_ops' from module 'lingvo.core.ops'; the following exception was raised: dynamic module does not define module export function (PyInit_x_ops) /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:21: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:39: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:57: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.pack_sequences:62: WARNING: Block quote ends without a blank line; unexpected unindent. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.apply_packing:23: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:22: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:24: WARNING: Block quote ends without a blank line; unexpected unindent. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:42: WARNING: Unexpected indentation. /home/ssd/junbo/repository/lingvo/lingvo/core/ops/__init__.py:docstring of lingvo.core.ops.mass:44: WARNING: Block quote ends without a blank line; unexpected unindent. /home/ssd/junbo/repository/lingvo/lingvo/tasks/car/ops/__init__.py:docstring of lingvo.tasks.car.ops.average_precision3d:35: WARNING: Unexpected indentation. WARNING: autodoc: failed to import module 'car_ops' from module 'lingvo.tasks.car.ops'; the following exception was raised: dynamic module does not define module export function (PyInit_car_ops)```

Do you have an idea for it? Thank you.
