### ISSUE TITLE
Distributed Shampoo Computing Preconditioners

### ISSUE THREAD

**Issue by stripathi08** [tensorflow/lingvo#207]
Hi, 
I'm trying port the distributed shampoo in pytorch but I'm unable to find any code for get/compute ops for preconditioned matrices. Any idea how can these functions be used with other frameworks?

```
x_ops.compute_preconditioners(
        stats, [-1.0 / (2.0 * r) for r in ranks],
        global_step_int32,
        keys=keys,
        sync=self._synchronous_preconditioning,
        preconditioner_compute_graphdef=self._preconditioner_compute_graphdef
)
```
Thanks,
Shubham

**Comment by jonathanasdf** [comment]
x_ops links to the C++ custom ops. this specific one is https://github.com/tensorflow/lingvo/blob/74e684489e1e2f214d9df311de009ca2d1355e8b/lingvo/core/ops/preconditioner_op_kernels.cc

**Comment by stripathi08** [comment]
Thanks Jonathan, this solves my problem. 
-Shubham
