### ISSUE TITLE
Why you should use Lingvo than T2T?

### ISSUE THREAD

**Issue by dyngts** [tensorflow/lingvo#21]
Hi Lingvo Devs,

TBH, i got confused when new library comes to offer similar features, After skimming the papers i found quiet similar with T2T. My only question is why we need Lingvo, instead using existing T2T to generate new idea? Thanks!

**Comment by nim456** [comment]
getting list index out of range error when I am running model training cell .....pls tell me how to fix this

tf.app.run(trainer.main, argv=argv)

getting list index out of range..........

**Comment by HawkAaron** [comment]
cause google has so many apartments, they want their own tools, each one maintain a independant tool.

Just ignore it, we don't need to follow them.

**Comment by drpngx** [comment]
Unfortunately it's hard to give a specific recommendation. Please refer to our paper for more details. My suggestion is for you to study both, as they have their own strengths and weaknesses that will affect you depending on what your use case is. I believe that you can achieve much of what you do in T2T with Lingvo and vice-versa. The Lingvo framework is designed for a mid to large team of researchers. For our own use, most of the researchers develop new models for speech and language applications.
