### ISSUE TITLE
Custom StarNetCyclist model underperforms

### ISSUE THREAD

**Issue by JWHennessey** [tensorflow/lingvo#223]
Hi, I've implemented a StarNet model for the cyclist class in the Waymo dataset. When I train it currently significantly underperforms compared to pedestrian and vehicles.

Are you able to share the hyper parameters you used to train this class specific model? 

Specifically:

- DIMENSION_PRIORS
- keep_z_range
- p.nms_iou_threshold[class_names.index('Cyclist')] 
- p.nms_score_threshold[class_names.index('Cyclist')] 

I've include the model below I am using incase there is anything I am missing. 

Thanks!

```
@model_registry.RegisterSingleTaskModel
class StarNetCyclist(StarNetBase):
  """StarNet model for Cyclist, running on Waymo."""
  NUM_ANCHOR_BBOX_ROTATIONS = 2
  GT_MIN_NUM_POINTS = 5

  class AnchorBoxSettings(input_preprocessors.SparseCarV1AnchorBoxSettings):
    DIMENSION_PRIORS = [(2.201340, 1.057218, 1.712443)]
    ROTATIONS = [0, np.pi / 2]
    CENTER_X_OFFSETS = np.linspace(-0.6, 0.6, 5)
    CENTER_Y_OFFSETS = np.linspace(-0.6, 0.6, 5)
    CENTER_Z_OFFSETS = [0.819622]

  def _configure_input(self, p, split):
    p = super(StarNetCyclist, self)._configure_input(p, split)

    # Select points in approx z range, set using 10 and 90 percentile from
    # train data.
    p.preprocessors.select_centers.features_preparation_layers = [
        input_preprocessors.DropLaserPointsOutOfRange.Params().Set(
            keep_z_range=(0.09522381, 1.920825)),
    ]

    _FilterKeepLabels(p, ['Cyclist'])
    return p

  def Task(self):
    p = super(StarNetCyclist, self).Task()
    p.train.l2_regularizer_weight = 3e-6

    class_names = waymo_metadata.WaymoMetadata().ClassNames()
    num_classes = len(class_names)

    p.per_class_loss_weight = [0.] * num_classes
    p.per_class_loss_weight[class_names.index('Cyclist')] = 1.0

    # See WaymoMetadata.EvalClassIndices for correspondences for metric_weights.
    p.output_decoder.ap_metric.metric_weights = {
        'default': np.array([0.0, 0.0, 1.0]),
    }
    p.nms_iou_threshold[class_names.index('Cyclist')] = 0.1
    p.nms_score_threshold[class_names.index('Cyclist')] = 0.15

    return p
```

**Comment by JWHennessey** [comment]
@vrv - Just tagging you here as you've been so helpful already :) Cheers!

**Comment by vrv** [comment]
Hi @JWHennessey we've actually never trained for cyclists on Waymo, so we don't have any settings optimized for that.

Two options / ideas:
- Use the same cyclist anchor box settings as for kitti: https://github.com/tensorflow/lingvo/blob/17c7d4032dbeca3e27f7feed55947392574d8263/lingvo/tasks/car/params/kitti.py#L520  -- perhaps only the last anchor box is needed, but it might still be a good idea to use 4 rotations.
- Analyze the labels of the cyclists to compute the mean dimensions of cyclists and use that as a more ideal "prior" -- you may also want to do this for CENTER_Z_OFFSETS settings, as well as the keep_z_range.

As for the other settings, they all seem reasonable.  Maybe start by setting nms_score_threshold to 0.01 for now.

**Comment by JWHennessey** [comment]
Thanks for the pointers as always! Much appreciated. Only a few days left in the competition :)

**Comment by vrv** [comment]
No problem, best of luck!

(Also, on KITTI, we had found that training peds and cyclists together was better than either of them separately, but that may be due to having very few cyclist labels in KITTI).
