### ISSUE TITLE
[solved] error in evaluating Test mnsit dataset

### ISSUE THREAD

**Issue by ramonsanabria** [tensorflow/lingvo#226]
running the evaluation code for the MNIST dataset provided in the README:

`
bazel-bin/lingvo/trainer --job=evaler_test --run_locally=cpu  --model=image.mnist.LeNet5 --logdir=/tmp/mnist/log --logtostderr
`

crushes with:
`
    assert cluster_params.mode == 'sync'
`

`
--mode=sync` should be added to the command, so the resulting (working) command is:
`
bazel-bin/lingvo/trainer --job=evaler_test --run_locally=cpu --mode=sync  --model=image.mnist.LeNet5 --logdir=/tmp/mnist/log --logtostderr
`

**Comment by jonathanasdf** [comment]
Thanks for the report. We will fix.
