### ISSUE TITLE
Gradient checkpoint / recomputation

### ISSUE THREAD

**Issue by eric-haibin-lin** [tensorflow/lingvo#239]
Does Lingvo support reducing model training memory with gradient checkpoint / recomputation on TF2?

**Comment by jonathanasdf** [comment]
Sequence models in Lingvo implemented using [recurrent.py](https://github.com/tensorflow/lingvo/blob/master/lingvo/core/recurrent.py) have some memory saving features by [recomputing the forward pass](https://github.com/tensorflow/lingvo/blob/20780f843f237cbc1c0bc34618c6521ea6557737/lingvo/core/recurrent.py#L737), and there are some implementations of [reversible layers](https://github.com/tensorflow/lingvo/blob/master/lingvo/core/reversible_layers.py). But there no general purpose tool like https://github.com/cybertronai/gradient-checkpointing.

**Comment by eric-haibin-lin** [comment]
Thanks!
