### ISSUE TITLE
InferenceGraphExporeter not working on MT example

### ISSUE THREAD

**Issue by soares-f** [tensorflow/lingvo#246]
Hi,

I've been trying to perform inference on a trained model on Lingvo, but I haven't had any success.
First I thought the problem was that I could have made a mistake while defining my own models, but then I tried with the example described here https://github.com/tensorflow/lingvo/tree/master/lingvo/tasks/mt and it did not work as well.

I trained the toy model for a few steps to get a checkpoint.
Then I tried the following:
```python
import string  

from lingvo import compat as tf  
from lingvo import model_imports 
from lingvo import model_registry
from lingvo.core import inference_graph_exporter
from lingvo.core import predictor
from lingvo.core.ops.hyps_pb2 import Hypothesis
tf.flags.FLAGS.mark_as_parsed()

PATH_CHECKPOINT = '/tmp/wmtm16/log/train'

checkpoint = tf.train.latest_checkpoint(PATH_CHECKPOINT)

params = model_registry.GetParams('mt.wmtm16_en_de.WmtCaptionEnDeTransformer', 'Test')
inference_graph = inference_graph_exporter.InferenceGraphExporter.Export(params)
```

I got the following error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/XXXX/ling38/lib/python3.8/site-packages/lingvo/core/inference_graph_exporter.py", line 433, in Export
    subgraphs_proto = task.Inference()
  File "/home/XXXX/ling38/lib/python3.8/site-packages/lingvo/core/base_model.py", line 748, in Inference
    raise NotImplementedError('Abstract method')
NotImplementedError: Abstract method
```

Checking the base_model.py it seems that it is not implemented.
However, when checking the colab introduction https://github.com/tensorflow/lingvo/blob/master/codelabs/introduction.ipynb,
this seems to be the appropriate steps.

Could anyone have any idea on how to solve this? I'm looking to make large scale inference on TPUs.

Best wishes,
Felipe

**Comment by jonathanasdf** [comment]
Hi Felipe,

I'm sorry to say that we don't have an open sourced Inference function defined for MT. Internally we use a different library for tokenization so the inference code is not compatible with the open source model.

You can take a look at examples from other tasks to implement the inference model, eg.
https://github.com/tensorflow/lingvo/blob/433fe73b55e767fb1ea75e126e3ea9b5ec134d98/lingvo/tasks/punctuator/model.py
https://github.com/tensorflow/lingvo/blob/508582df5ff5da3a8a92dbe38f123e1b62f7784f/lingvo/tasks/image/classifier.py
https://github.com/tensorflow/lingvo/blob/e99eaa47090cbb66886c8210b6650b74e39fe967/lingvo/tasks/asr/model.py

Hope that helps,
Jonathan
