### ISSUE TITLE
Error when running gshard dense transformer on gcp tpus

### ISSUE THREAD

**Issue by chadwickleung** [tensorflow/lingvo#266]
Hi, I got the following error while trying to run the gshard DenseLm128B8x8 on gcp tpus:

RuntimeError: Actual list of devices does not match cluster configuration: Expected 1 CPU devices in 8 replicas but got ['/job:executor_tpu/replica:0/task:0/device:CPU:0', '/job:executor_tpu/replica:0/task:1/device:CPU:0', '/job:executor_tpu/replica:0/task:2/device:CPU:0', '/job:executor_tpu/replica:0/task:3/device:CPU:0', '/job:executor_tpu/replica:0/task:4/device:CPU:0', '/job:executor_tpu/replica:0/task:5/device:CPU:0', '/job:executor_tpu/replica:0/task:6/device:CPU:0', '/job:executor_tpu/replica:0/task:7/device:CPU:0', '/job:executor_tpu/replica:0/task:8/device:CPU:0', '/job:executor_tpu/replica:0/task:9/device:CPU:0', '/job:executor_tpu/replica:0/task:10/device:CPU:0', '/job:executor_tpu/replica:0/task:11/device:CPU:0', '/job:executor_tpu/replica:0/task:12/device:CPU:0', '/job:executor_tpu/replica:0/task:13/device:CPU:0', '/job:executor_tpu/replica:0/task:14/device:CPU:0', '/job:executor_tpu/replica:0/task:15/device:CPU:0'] for {
  additional_worker_names: []
  cpus_per_replica: 1
  devices_per_split: 1
  gpus_per_replica: 0
  name: "/job:executor_tpu"
  num_tpu_hosts: 0
  replicas: 8
  targets: ""
  tpus_per_replica: 0
}.

I followed the instructions specified on the lm readme, created a vm instance, a v3-128 node with software version 2.4.1,  and have only modified max_steps, warmup_steps, and save_max_to_keep of p.train under Task() before running it.

**Comment by bignamehyp** [comment]
What's your exact cmd? Can you please try to use ps_replicas=16 instead?

**Comment by chadwickleung** [comment]
It works, thank you! I guess it's because it's 8 node per host?
