### ISSUE TITLE
Cross Attention

### ISSUE THREAD

**Issue by wcshen** [tensorflow/lingvo#284]
I am new to lingvo and I would like to know where to find the code for Cross Attention in 
`DeepFusion: Lidar-Camera Deep Fusion for Multi-Modal 3D Object Detection`?

**Comment by LiYingwei** [comment]
We are still working on releasing the code. You should be able to find the code here later: https://github.com/tensorflow/lingvo/tree/master/lingvo/tasks/car

Thanks for your patience!

**Comment by javiercalle97** [comment]
Could you tell us when the code will be released? Thanks in advance!

**Comment by LiYingwei** [comment]
We just released the code, and here is the CrossAttention implementation
https://github.com/tensorflow/lingvo/blob/6b75b054aa78b0db3adebd564ee21ba1afff86fd/lingvo/tasks/car/deep_fusion.py#L287

**Comment by wcshen** [comment]
thanks
