### ISSUE TITLE
DeepFusion Learnable Align Impl Details

### ISSUE THREAD

**Issue by OrcunCanDeniz** [tensorflow/lingvo#289]
In the paper, It is said that there are implementation details about LearnableAlign in the supplementary materials. However I couldnt find a version of the paper containing that content. Could you please point me to it? 

Thanks.

**Comment by LiYingwei** [comment]
Here is the code for LearnableAlign: https://github.com/tensorflow/lingvo/blob/6b75b054aa78b0db3adebd564ee21ba1afff86fd/lingvo/tasks/car/deep_fusion.py#L287
