### ISSUE TITLE
bazel build error

### ISSUE THREAD

**Issue by wukong4430** [tensorflow/lingvo#38]
DEBUG: Rule 'subpar' modified arguments {"commit": "07ff5feb7c7b113eea593eb6ec50b51099cf0261", "shallow_since": "1524766240 -0700"} and dropped ["tag"]
ERROR: /home/sck/gitRepo/lingvo/lingvo/core/ops/BUILD:277:1: no such package '@tensorflow_includes//': Traceback (most recent call last):
        File "/home/sck/gitRepo/lingvo/lingvo/repo.bzl", line 70
                _find_tf_include_path(repo_ctx)
        File "/home/sck/gitRepo/lingvo/lingvo/repo.bzl", line 16, in _find_tf_include_path
                fail("Could not locate tensorflow ins...")
Could not locate tensorflow installation path. and referenced by '//lingvo/core/ops:tokenizer_ops_kernels'
ERROR: Analysis of target '//lingvo:trainer' failed; build aborted: no such package '@tensorflow_includes//': Traceback (most recent call last):
        File "/home/sck/gitRepo/lingvo/lingvo/repo.bzl", line 70
                _find_tf_include_path(repo_ctx)
        File "/home/sck/gitRepo/lingvo/lingvo/repo.bzl", line 16, in _find_tf_include_path
                fail("Could not locate tensorflow ins...")
Could not locate tensorflow installation path.

I was using a conda virtual env and I've install tensorflow for it.. So how could i make it locate tensorflow installation path. Thanks

**Comment by Raviteja1996** [comment]
How were you able to solve the issue?

**Comment by arr00** [comment]
How did you fix this? I have the exact same issue.

**Comment by drpngx** [comment]
The way it tries to find the install path is by issuing the following command:
```
python3 -c 'import tensorflow as tf; import sys; sys.stdout.write(tf.sysconfig.get_include())'
```
(Yes, it doesn't print the endline character.) Try this from the command-line and see what happens.

**Comment by arr00** [comment]
I got it working by installing tensorflow. Had tensorflow-gpu installed. Thanks
