### ISSUE TITLE
how could I set params like max_steps

### ISSUE THREAD

**Issue by daiwk** [tensorflow/lingvo#40]
When I ran the example of mnist, I found the hyperparams are set to default values like follows:

> task.train.max_steps : 4000000

but where can I set these params? Would I have to directly modify lingvo/tasks/image/params/mnist.py  or some code else?

**Comment by drpngx** [comment]
Yes, you would modify that file. So to be able to distinguish experiments later, the best practice is to create a new "model" in the `mnist.py` file:

```
@model_registry.RegisterSingleTaskModel
class LeNet5TrainedLonger(LeNet5):

  @classmethod
  def Task(cls):
    p = super(LeNet5TrainLonger, cls).Task()
    p.train.max_steps = 100000000
    return p
```

**Comment by daiwk** [comment]
@drpngx thx for your answer~My problem has been solved
