### ISSUE TITLE
Seq2Seq models for TTS 

### ISSUE THREAD

**Issue by marzieh-razavi** [tensorflow/lingvo#44]
Is there any plan to add the seq2seq models for the text-to-speech task as well?

**Comment by jonathanasdf** [comment]
Sorry, we will not be announcing any future plans in this forum.

When we release new models, we will make sure to put a notice on the front page for a while, and if it's a major model we may put a blog post on the Tensorflow and/or Google AI blog + tweets. Please use these resources to track if a model you're interested in is being released.
