### ISSUE TITLE
Lingvo Docker Sharing Now!!!

### ISSUE THREAD

**Issue by BigFishMaster** [tensorflow/lingvo#45]
I have built a lingvo docker on [dockerhub](https://hub.docker.com/r/chriscxyan/tensorflow-lingvo-tf12
) . Nvidia-cuda-10 needs docker-v2, which is not supported by my work env. Thus I use the following settting:
```
tensorflow: gpu, v1.12.0
lingvo: master
cuda: 9.0
docker: nvidia-docker (not "-v2")
```
![image](https://user-images.githubusercontent.com/4915869/54339076-bba4d700-466e-11e9-8f09-54f024158967.png)

**Comment by drpngx** [comment]
Neat, thanks @BigFishMaster !

Closing now.
