### ISSUE TITLE
training punctuator in notebook crashed 

### ISSUE THREAD

**Issue by weiDialpad** [tensorflow/lingvo#46]
bazel run -c opt //lingvo:trainer -- --logtostderr --model=punctuator.codelab.RNMTModel --mode=sync --logdir=/tmp/punctuator --saver_max_to_keep=2 --run_locally=cpu --enable_asserts=false

From the command line or notebook, have the same problem as following:
...
...
I0316 18:10:57.939176 139757224118016 base_runner.py:115] step:     0
W0316 18:11:00.613759 139757240633088 meta_graph.py:447] Issue encountered when serializing __batch_norm_update_dict.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'dict' object has no attribute 'name'
W0316 18:11:00.614701 139757240633088 meta_graph.py:447] Issue encountered when serializing __model_split_id_stack.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'list' object has no attribute 'name'
I0316 18:11:01.184139 139757240633088 trainer.py:270] Save checkpoint done: /tmp/punctuator/train/ckpt-00000000
I0316 18:11:01.189898 139757240633088 trainer.py:371] Steps/second: 0.000000, Examples/second: 0.000000
I0316 18:11:11.201571 139757240633088 trainer.py:371] Steps/second: 0.000000, Examples/second: 0.000000
2019-03-16 18:11:18.382848: I ./lingvo/core/ops/input_common.h:63] Create RecordProcessor
2019-03-16 18:11:18.551229: I lingvo/core/ops/input_common.cc:28] Input source weights are empty, fall back to legacy behavior.
2019-03-16 18:11:18.551383: I lingvo/core/ops/record_yielder.cc:167] 0x7f1bb518f940 Record 
yielder start
2019-03-16 18:11:18.551424: I lingvo/core/ops/record_yielder.cc:169] Randomly seed RecordYielder.
2019-03-16 18:11:18.551447: I ./lingvo/core/ops/input_common.h:68] Create batcher
2019-03-16 18:11:18.551517: I lingvo/core/ops/record_yielder.cc:217] Epoch 1 /tmp/punctuator_data/train.txt
I0316 18:11:24.267724 139757240633088 trainer.py:371] Steps/second: 0.000000, Examples/second: 0.000000
I0316 18:11:31.178570 139757240633088 trainer.py:371] Steps/second: 0.000000, Examples/second: 0.000000
I0316 18:11:41.254617 139757240633088 trainer.py:371] Steps/second: 0.000000, Examples/second: 0.000000
Killed

**Comment by jonathanasdf** [comment]
I think a sudden "Killed" could be because of OOM issues, or also disk space issues. Can you check your CPU & GPU memory usage as well as disk free space?

**Comment by weiDialpad** [comment]
I limited the train.txt to 100 lines, very small. But still got the same error.

**Comment by drpngx** [comment]
It's about the size of the model. You can take a look at `dmesg` output. You would typically see something about process sacrificed.
