### ISSUE TITLE
Error while trying to run Gpipe example

### ISSUE THREAD

**Issue by Raviteja1996** [tensorflow/lingvo#53]
Hi, as I was getting error #49 . Now i tried to do it in another environment. And i am facing the below problem when i try to run the command: **bazel build -c opt //lingvo:trainer**. Before running the main command which was specified to me in #48 i am running the above command before it in the home directory. Please tell me if I am doing any step wrong.

**ERROR : **
[Gpipe_error.txt](https://github.com/tensorflow/lingvo/files/3007285/Gpipe_error.txt)

**Comment by drpngx** [comment]
It looks like you are missing `libcuda.so.1`. Please find where it is (typically somewhere in `/usr/lib/python2.7/dist-packages/_so_lib`, and add that path to the `LD_LIBRARY_PATH` environment variable before building.

**Comment by Raviteja1996** [comment]
I am still getting the same error as before which I posted(text file).

**Comment by drpngx** [comment]
Do you locate the library? Can you run `ld` on it to see if the symbol is defined there? It could be the wrong version.

**Comment by Raviteja1996** [comment]
Hi, I searched for the libcuda.so.1 and found few of them. When I did **nm** for the path to the filename along with the file name I got "no symbols" as output. I got this for all the libcuda.so.1 files which appeared when I searched for them.

**Comment by drpngx** [comment]
It looks like the CUDA library was improperly installed. Please try installing again.
