### ISSUE TITLE
trainer_test not pass 

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/lingvo#54]
[test.log](https://github.com/tensorflow/lingvo/files/3007387/test.log)
[test.log](https://github.com/tensorflow/lingvo/files/3007389/test.log)
[test.log](https://github.com/tensorflow/lingvo/files/3007392/test.log)

== cat /etc/issue ===============================================
Linux ml-gpu-ser341.nmg01 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.5 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
Yes

== compiler =====================================================
c++ (Ubuntu 4.8.5-4ubuntu2) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== bazel =====================================================
Build label: 0.17.2
Build time: Fri Sep 21 10:31:42 2018 (1537525902)
Build timestamp: 1537525902
Build timestamp as int: 1537525902

== uname -a =====================================================
Linux ml-gpu-ser341.nmg01 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                              1.16.2              
protobuf                           3.7.0               

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.14.1-dev20190324
tf.GIT_VERSION = v1.12.0-10956-g044ff96ba3
tf.COMPILER_VERSION = v1.12.0-10956-g044ff96ba3
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/local/nvidia/lib64/:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 109: nvidia-smi: command not found

== cuda libs  ===================================================
/usr/local/cuda-10.0/lib64/libcudart_static.a
/usr/local/cuda-10.0/lib64/libcudart.so.10.0.130
/usr/local/cuda-10.0/doc/man/man7/libcudart.7
/usr/local/cuda-10.0/doc/man/man7/libcudart.so.7

**Comment by drpngx** [comment]
The "failed to allocate memory" is probably because you have another tensorflow process on the same machine. Tensorflow allocates the whole GPU memory to itself by default.

Does this happen every time?

**Comment by drpngx** [comment]
It looks like you have to run with `--jobs=1` to prevent the tests from clashing with each other.

**Comment by zh794390558** [comment]
when i test, all gpu is not working, and I can not control gpu visible via CUDA_VISIBILE_DEVICES .
