### ISSUE TITLE
Could not locate tensorflow installation path.

### ISSUE THREAD

**Issue by Raviteja1996** [tensorflow/lingvo#56]
Hi, as you told in #49 that supported version was ubuntu 16. So I was also trying to run on another system which consists of ubuntu 16. But I was facing Could not locate tensorflow path everytime. But I do have tensorflow installed in my system.

Command : bazel build -c opt //lingvo:trainer
output:
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
DEBUG: Rule 'subpar' modified arguments {"commit": "07ff5feb7c7b113eea593eb6ec50b51099cf0261", "shallow_since": "1524766240 -0700"} and dropped ["tag"]
ERROR: /home/guest/lingvo/lingvo/core/ops/BUILD:24:1: no such package '@tensorflow_includes//': Traceback (most recent call last):
        File "/home/guest/lingvo/lingvo/repo.bzl", line 70
                _find_tf_include_path(repo_ctx)
        File "/home/guest/lingvo/lingvo/repo.bzl", line 16, in _find_tf_include_path
                fail("Could not locate tensorflow ins...")
Could not locate tensorflow installation path. and referenced by '//lingvo/core/ops:x_ops'
ERROR: Analysis of target '//lingvo:trainer' failed; build aborted: no such package '@tensorflow_includes//': Traceback (most recent call last):
        File "/home/guest/lingvo/lingvo/repo.bzl", line 70
                _find_tf_include_path(repo_ctx)
        File "/home/guest/lingvo/lingvo/repo.bzl", line 16, in _find_tf_include_path
                fail("Could not locate tensorflow ins...")
Could not locate tensorflow installation path.
INFO: Elapsed time: 1.193s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 24 targets configured)
    Fetching @protobuf_protoc; fetching
    Fetching @tensorflow_solib; fetching
    Fetching @tensorflow_includes; fetching

**Comment by jonathanasdf** [comment]
It's just running this command: https://github.com/tensorflow/lingvo/blob/10cabfd71a7e8bd7c0dee010862c913c0015dea4/lingvo/repo.bzl#L8

Try running the command manually and figure out why it's not locating it. Maybe python vs python3?

**Comment by Raviteja1996** [comment]
Hi I think what you said was right! I had python3 before now I installed tensorflow with python but now I was facing another error. I am attaching the error log.

[Gpipe_err.txt](https://github.com/tensorflow/lingvo/files/3021307/Gpipe_err.txt)

**Comment by jonathanasdf** [comment]
It seems you installed tensorflow, but we need tf-nightly instead.

Please pip install tf-nightly (make sure you're using the correct pip of course)

**Comment by Raviteja1996** [comment]
thank you, it got resolved.

**Comment by Raviteja1996** [comment]
tf-nightly version : 1.14.1.dev20190331 is only working while using python. When I tried to use version greater than that it showing error and was not able to build.
