### ISSUE TITLE
MaskGradients doc string error

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/lingvo#57]
https://github.com/tensorflow/lingvo/blob/master/lingvo/core/py_utils.py#L1381

The docstring of function `def MaskGradients(var_grad, grad_mask, grad_onehot)` is wrong, and I do not know the function of this method.

**Comment by jonathanasdf** [comment]
I think it is almost right, but grad_mask should be (variable_name, mask). Is that what you mean?

**Comment by zh794390558** [comment]
Yes, but `Computes gradients of variables in vmap w.r.t. loss.`  does it right? It is same to `ComputeGradients`, and I think this method is not for computing gradients.

**Comment by jonathanasdf** [comment]
Ah, I see what you mean now. Will look into it.
