### ISSUE TITLE
Error while trying to do "bazel build -c opt //lingvo:trainer"

### ISSUE THREAD

**Issue by Raviteja1996** [tensorflow/lingvo#61]
Hi, I am using ubuntu 18, my bazel version is 0.23.2 and my gcc version is 7.3.0. I am getting the following error when trying to execute the commad **"bazel build -c opt //lingvo:trainer"**

Error:
[bazel_error.txt](https://github.com/tensorflow/lingvo/files/3032214/bazel_error.txt)

**Comment by jonathanasdf** [comment]
That's the same error as https://github.com/tensorflow/lingvo/issues/56#issuecomment-477877370

It should be fixed if you are using tf-nightly(-gpu) instead of tensorflow(-gpu)

**Comment by Raviteja1996** [comment]
Yeah, I got it resolved. I was having tf-nightly but this was a different error. So following the post #56 Having the same versions I was able to overcome the problem. Thank you.

**Comment by Raviteja1996** [comment]
Even while using python. tf-nightly version : 1.14.1.dev20190331 is only working. Any version greater than this, error is being shown.

**Comment by jonathanasdf** [comment]
Thanks, we are sending out fix for this.
