### ISSUE TITLE
not exits `models.py` file

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/lingvo#62]
https://github.com/tensorflow/lingvo/blob/31f600844d28eba5232c2f37764db262be5c6d0c/lingvo/trainer.py#L59

I can not find `models.py` under this repo.

**Comment by drpngx** [comment]
Can you clarify what the problem is? The models are in different files.

**Comment by zh794390558** [comment]
`Name of the model class to train. Must be one of those defined in models.py` the comments reference  `models.py`.

**Comment by drpngx** [comment]
Oh, right, fix is coming.
