### ISSUE TITLE
Getting segmentation fault while trying to run Gpipe example code

### ISSUE THREAD

**Issue by Raviteja1996** [tensorflow/lingvo#63]
Hi, as you mentioned in #48 about changing OneBWdsGPipeTransformer hparams and then try to run on 8 GPU's and gave the command to run. I did not understand what are those parameters, can I get help which parameters fit for my system. I am using machine consisting of 4 GPU. What ever the parameters I change I am facing segmentation fault core dumped. I am also attaching my system info(GPU).

**command :** bazel-bin/lingvo/trainer --run_locally=gpu --mode=sync --model=lm.one_billion_wds.OneBWdsGPipeTransformer --logdir=/tmp/mnist/log --logtostderr --worker_split_size=4
[segmentation fault.txt](https://github.com/tensorflow/lingvo/files/3042889/segmentation.fault.txt)

system info:
GPU:
[sys_info.txt](https://github.com/tensorflow/lingvo/files/3042913/sys_info.txt)

**Comment by drpngx** [comment]
It's strange that you would be getting SEGV without any output. Try setting the environment variable `TF_CPP_MIN_LOG_LEVEL` to zero and rerun. Also, please rerun within GDB and tell us where the program crashed.

**Comment by Raviteja1996** [comment]
Hi, I know how to use gdb normally, but I do not know how to use in this case. Can you help me with that!

**Comment by drpngx** [comment]
Just run the program with `gdb --args`. Then `run` at the prompt. Once it crashes, type `where` to display all stack locations of all threads.

**Comment by Raviteja1996** [comment]
Hi, I am facing the following problem while trying to do gdb:
"/home/guest/lingvo/bazel-bin/lingvo/trainer": not in executable format: File format not recognized
(gdb) run
Starting program:  --run_locally=gpu --mode=sync --model=lm.one_billion_wds.OneBWdsGPipeTransformer --logdir=/tmp/mnist/log --logtostderr --worker_split_size=4
No executable file specified.
Use the "file" or "exec-file" command.

**Comment by drpngx** [comment]
Oh, right, sorry. It's a bit more complicated.

OK, first, let's try to see the logs by running `env TF_CPP_MIN_LOG_LEVEL=1 /home/guest/lingvo/bazel-bin/lingvo/trainer`.

**Comment by Raviteja1996** [comment]
Hi, after running the above command **env TF_CPP_MIN_LOG_LEVEL=1 /home/guest/lingvo/bazel-bin/lingvo/trainer** I got the following, I am attaching it in a text file:
[output_log.txt](https://github.com/tensorflow/lingvo/files/3061587/output_log.txt)

**Comment by Raviteja1996** [comment]
Hi , I went and did **gdb python ./core**, and did a **where** in gdb, so this was the output. I did this maybe something will be related to this:

[gdb-where.txt](https://github.com/tensorflow/lingvo/files/3061958/gdb-where.txt)

**Comment by Raviteja1996** [comment]
Hi any update/solution for the above.

**Comment by Raviteja1996** [comment]
Hi any update/solution for the above.

**Comment by rlundberg-g** [comment]
I am running into a similar issue (Segmentation fault) just trying to run the image/mnist example described in the /README.md file. Installed everything directly (not using docker).
tensorflow version: 1.14.1-dev20190412.
g++ version: (Debian 7.3.0-5) 7.3.0

[mnist_segfault.txt](https://github.com/tensorflow/lingvo/files/3080058/mnist_segfault.txt)

**Comment by jonathanasdf** [comment]
If docker worked fine then it's probably some package version issue. Unfortunately we're not going to try to support all configurations.

> Hi , I went and did **gdb python ./core**, and did a **where** in gdb, so this was the output. I did this maybe something will be related to this:
> 
> [gdb-where.txt](https://github.com/tensorflow/lingvo/files/3061958/gdb-where.txt)

Since there's a reference to /usr/include/c++/7 is it possible you are using g++ version 7 (check g++ --version). If so it might be that lingvo does not work with g++7 like https://github.com/tensorflow/lingvo/issues/63#issuecomment-483233100 implies.
