### ISSUE TITLE
Error while trying to run using docker

### ISSUE THREAD

**Issue by Raviteja1996** [tensorflow/lingvo#67]
Hi, when I tried to do it directly without docker, I was facing many problems but didn't find a solution. Now I tried using docker and I am facing the following error when I run the command,
**command** **:** bazel build -c opt //lingvo:trainer
**Error:**
INFO: Analysed target //lingvo:trainer (0 packages loaded).
INFO: Found 1 target...
ERROR: missing input file '@tensorflow_solib//:tensorflow_solib/libtensorflow_framework.so'
ERROR: /tmp/lingvo/lingvo/BUILD:150:1: Creating runfiles tree bazel-out/k8-opt/bin/lingvo/trainer.runfiles failed: Process terminated by signal 15: Process terminated by signal 15
ERROR: /root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/external/tensorflow_solib/BUILD:2:1: @tensorflow_solib//:framework_lib: missing input file '@tensorflow_solib//:tensorflow_solib/libtensorflow_framework.so'
Target //lingvo:trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/external/tensorflow_solib/BUILD:2:1 1 input file(s) do not exist
INFO: Elapsed time: 0.195s, Critical Path: 0.01s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by jonathanasdf** [comment]
Hi, if you can, can you please write down how you solved this so if others have the same problem in the future they have a potential solution?

**Comment by Raviteja1996** [comment]
I tried directly before without docker, so there was cache of that. I went and removed the 'bazel' folder from the cache and tried to do with the docker again. It ran fine.

**Comment by zhangdong1992** [comment]
I have the same problem. I removed the 'bazel' folder form the cache, but the error did not solved. Who knows why?

**Comment by RoKish** [comment]
I've also faced the problem. Any updates on this?

**Comment by fanshiqing** [comment]
I met the same problem when I want to build a centos7 docker step by step. Any updates? @Raviteja1996

**Comment by gf-sdu** [comment]
I met the same problem when I want to build a ubuntu docker step by step
