### ISSUE TITLE
Error when running docker

### ISSUE THREAD

**Issue by iamxiaoyubei** [tensorflow/lingvo#69]
I have build docker successfully before. 

`sudo docker build --tag tensorflow:lingvo $(test "$LINGVO_DEVICE" = "gpu" && echo "--build-arg base_image=nvidia/cuda:10.0-cudnn7-runtime-ubuntu16.04") - < ${LINGVO_DIR}/docker/dev.dockerfile

Sending build context to Docker daemon   5.12kB

Step 1/19 : ARG cpu_base_image="ubuntu:16.04"

Step 2/19 : ARG base_image=$cpu_base_image

Step 3/19 : FROM $base_image

10.0-cudnn7-runtime-ubuntu16.04: Pulling from nvidia/cuda

34667c7e4631: Pull complete 

d18d76a881a4: Pull complete 

119c7358fbfc: Pull complete 

2aaf13f3eff0: Pull complete 

643564d518c8: Pull complete 

1fea03e629a4: Pull complete 

45402f4cf61d: Pull complete 

86f75b2a221d: Downloading 

9e547bd511ba: Download complete 

EOF`

But when I run docker:
`sudo docker run --rm $(test "$LINGVO_DEVICE" = "gpu" && echo "--runtime=nvidia") -it -v ${LINGVO_DIR}:/tmp/lingvo -v ${HOME}/.gitconfig:/home/${USER}/.gitconfig:ro -p 6006:6006 -p 8888:8888 --name lingvo tensorflow:lingvo bash`

I got the following error:
`docker: Error response from daemon: Unknown runtime specified nvidia`

Have someone meet the same problem with me? Thanks!

**Comment by jonathanasdf** [comment]
To run on GPU you need to install nvidia-docker2 https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)

**Comment by iamxiaoyubei** [comment]
@jonathanasdf Thanks. Using your method, it solved.

**Comment by iamxiaoyubei** [comment]
But when running docker, it occurs an error again:

`sudo docker run --rm $(test "$LINGVO_DEVICE" = "gpu" && echo "--runtime=nvidia") -it -v ${LINGVO_DIR}:/tmp/lingvo -v ${HOME}/.gitconfig:/home/${USER}/.gitconfig:ro -p 6006:6006 -p 8888:8888 --name lingvo tensorflow:lingvo bash`
`Unable to find image 'tensorflow:lingvo' locally`

`docker: Error response from daemon: pull access denied for tensorflow, repository does not exist or may require 'docker login'.`
`See 'docker run --help'.`

**Comment by iamxiaoyubei** [comment]
Solved.
Need build docker again.
