### ISSUE TITLE
What is controller_gpus/worker_gpus/ps_gpus/evaler_gpus/decoder_gpus?

### ISSUE THREAD

**Issue by iamxiaoyubei** [tensorflow/lingvo#74]
Hi, I use this script to run asr task:
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 bazel-bin/lingvo/trainer --run_locally=gpu --mode=sync --model=asr.librispeech.Librispeech960Wpm --logdir=/tmp/librispeech/log --logtostderr --enable_asserts=false
```
And I have 8 GPU to run this experiment. However, it only uses one gpu.

![Screenshot from 2019-04-28 11-35-17](https://user-images.githubusercontent.com/21981293/56859540-290e8c00-69bf-11e9-8286-1580d506e0cc.png)

So, I think it must be some parameters to change. Then, I found controller_gpus/worker_gpus/ps_gpus/evaler_gpus/decoder_gpus in lingvo/trainer.py. 

Could you mind tell me what is the meaning of controller_gpus/worker_gpus/ps_gpus/evaler_gpus/decoder_gpus? Which should I change to run this task on multi GPU?

I tried set worker_gpus to 8. Then the memory of all GPUs is indeed occupied, but the utilization is still not very high, so I am not sure whether I set correctly.

**Comment by jonathanasdf** [comment]
yes, worker_gpus is the one you should set and other ones you can ignore. if gpu utilization is low you can try increasing batch size.

**Comment by iamxiaoyubei** [comment]
@jonathanasdf 
Thanks.

**Comment by iamxiaoyubei** [comment]
Thanks~
