### ISSUE TITLE
What's the difference between 'sync' mode and 'async' mode?

### ISSUE THREAD

**Issue by iamxiaoyubei** [tensorflow/lingvo#76]
It seems that we can train on multiple GPUs regardless of whether the mode is set to synchronous or asynchronous. So, could you mind tell me what's the difference of 'sync' mode and 'async' mode? What are their respective advantages?

**Comment by jonathanasdf** [comment]
It is the same as in core Tensorflow, eg. https://www.tensorflow.org/alpha/guide/distribute_strategy

A good summary is "Synchronous versus asynchronous distributed training" in https://www.oreilly.com/ideas/distributed-tensorflow
