### ISSUE TITLE
Training ASR models with gpus get exception "Resource exhausted: OOM"

### ISSUE THREAD

**Issue by EmpRamses** [tensorflow/lingvo#80]
<img width="635" alt="屏幕快照 2019-05-08 上午9 49 30" src="https://user-images.githubusercontent.com/10172561/57343634-b6e43700-7176-11e9-9f51-a2d96af5a3c6.png">
These are my gpus. I tried to use them to train both asr models with command following:

> bazel-bin/lingvo/trainer --run_locally=gpu --mode=sync --worker_gpus=2 --logdir=/tmp/librispeech/log --model=asr.librispeech.Librispeech960Wpm --logtostderr --enable_asserts=false >& /tmp/librispeech/log/train.log

The trainer.py process got the exception before training process start. But it can run on cpu.

So, how can I train these models with my gpus?

**Comment by jonathanasdf** [comment]
It is strange you are getting OOM with 12GB memory but you can try reducing batch size here

https://github.com/tensorflow/lingvo/blob/e649e651e80ec1ad092a4d6777486ace5ea2c3f9/lingvo/tasks/asr/params/librispeech.py#L65

**Comment by EmpRamses** [comment]
@jonathanasdf Thank you! I reduce batch sizes to their half. It works. But the training process still use 11GB memory in each gpu.
<img width="643" alt="屏幕快照 2019-05-08 上午10 20 37" src="https://user-images.githubusercontent.com/10172561/57344927-af735c80-717b-11e9-8314-c978daa29888.png">

**Comment by jonathanasdf** [comment]
That is because of how tensorflow works, see eg. https://stackoverflow.com/questions/46085874/occupies-all-gpu-memory-with-the-following-tensorflow-code

**Comment by EmpRamses** [comment]
Ahhh... I know that. It seems that on gpu memory limiting configure in trainer.py
