### ISSUE TITLE
Could you mind tell me which papers are you referring to to write ASR Task?

### ISSUE THREAD

**Issue by iamxiaoyubei** [tensorflow/lingvo#82]
I am currently looking at the code of your ASR Task. But I found that many of the codes inside are difficult to understand, especially the decoder part. So I hope to find some references to help understand and learn. Could you mind tell me which papers are you referring to to write ASR Task? Thank you so much!!

**Comment by iamxiaoyubei** [comment]
The main thing is not to understand why some ways can be used. I don't quite understand why you can replace the acoustic model and the language model into an end-to-end manner, and which part of the network can do their job separately.

**Comment by iamxiaoyubei** [comment]
I feel that the network structure in the code is very similar to the network structure in the [paper](https://arxiv.org/pdf/1703.08581.pdf) 3.1.Speech model.  Is it a variation of [Very Deep Convolutional Networks for End-to-End Speech Recognition](https://arxiv.org/pdf/1610.03022.pdf)?  But why you comment "the implementation of attention here follows the model in
https://arxiv.org/pdf/1609.08144.pdf"

**Comment by rprabhavalkar** [comment]
Hi. Please find answers to your questions below:

- I think the best way to think about this is that the ASR encoder code [here](https://github.com/tensorflow/lingvo/blob/master/lingvo/tasks/asr/encoder.py): allows for a variety of architectures (e.g., the structures described in the "Very Deep Convolutional Networks" paper you reference above). The structure that we actually use depends on the specific task that we are working on. For example, on Librispeech, the structure that we use is described in this [recent paper](https://arxiv.org/abs/1904.08779)

- In terms of the "main papers" I would suggest looking at the most recent papers. In particular, I'd suggest looking at:
[1] C.-C.Chiu, T. N. Sainath, Y. Wu, R. Prabhavalkar, P. Nguyen, Z. Chen, A. Kannan, R. J. Weiss, K. Rao, K. Gonina, N. Jaitly, B. Li, J. Chorowski, and M. Bacchiani, “State-of-the-art speech recognition with sequence-to-sequence models,” in Proc. IEEE International Conference on Acoustics, Speech, and Signal Processing (ICASSP), 2018.
[2] D. S. Park, W. Chan, Y. Zhang, C.-C. Chiu, B. Zoph, E. D. Cubuk, Q. V. Le, "SpecAugment: A Simple Data Augmentation Method for Automatic Speech Recognition," arXiv e-prints, arXiv:1904.08779, 2019.

Hope that's helpful.
Rohit.

**Comment by iamxiaoyubei** [comment]
Thank you very much! :)

**Comment by pehonnet** [comment]
Hi,

You say that the structure used is described in the SpecAugment paper. Do you mean that it is including the SpecAugment work? Or simply that the model is the same, but not train with the SpecAugment strategy? If the second option, is there any training script including SpecAugment? Or a plan to provide on in the lingvo framework?

Thanks for clarifying.

**Comment by datavizweb** [comment]
SpecAugment implementation is here, I am not sure it is complete [https://github.com/tensorflow/lingvo/blob/d69097114d45af6281496b6a8fa1242b58e7e0b0/lingvo/core/spectrum_augmenter.py](url)

**Comment by jonathanasdf** [comment]
The implementation is currently incomplete. We are trying to figure out how to deal with some tf.contrib functions that are disappearing in TF2.0.

**Comment by datavizweb** [comment]
@jonathanasdf how the TF 2.0 migration (push) is going to affect the Lingvo? I believe, the trainer, client , evaler might require some changes as there are no sessions. What about the models, layers. I still see commits being added to Lingvo and don't see how the TF 2.0 migration and Lingvo framework converge in future.

**Comment by jonathanasdf** [comment]
Lingvo will stay with tf.compat.v1 for now and slowly transition to 2.0 bit by bit.
