### ISSUE TITLE
Could I use my own corpus to train word piece vocabulary using your codes?

### ISSUE THREAD

**Issue by iamxiaoyubei** [tensorflow/lingvo#86]
Hello. May I ask how your "wpm_16k_librispeech.vocab" is trained?

Could I use my own corpus to train word piece vocabulary using your codes? If there are some codes in your repo to train the word piece model, could you tell me how to use it? (I haven't found it so far.)

Thank you!

**Comment by iamxiaoyubei** [comment]
I saw the [sentencepiece open source package](https://github.com/google/sentencepiece). Can I train a .vocab with this package and then use the asr.librispeech.Librispeech960Wpm model?

What is the difference between your wordpiece and sentencepiece?

**Comment by drpngx** [comment]
I don't quite know if sentence piece is compatible at runtime with word
piece unfortunately. It's possible. I would suggest to give it a try. The
only thing is that the vocab file must be sorted in decreasing order of
merge priority.

We don't provide training unfortunately. There is also BPE iirc.

Alternatively you can implement your own. It should be straightforward
except if you want it to run fast.

**Comment by iamxiaoyubei** [comment]
Thank you very much for your prompt response. I will try it!

**Comment by muntasir2000** [comment]
Did you try to build your own .vocab file using sentencepiece library? I also have to build my own .vocab file.
