### ISSUE TITLE
Lingvo: Basic bazel test case failure 

### ISSUE THREAD

**Issue by msharmavikram** [tensorflow/lingvo#89]
Hi there,

I am trying to build Lingvo using the docker container approach provided in the README.md 

After successful docker builds, when I run `bazel test -c opt //lingvo:trainer_test //lingvo:models_test
` command, I see 3 out of 5 test case fail in the `trainer_test`. The issue comes from the fact that the CUDA ran out of the memory. It seems like the test case is trying to allocate more memory than available (i am not sure why). I wonder how much memory is required for the basic test case to pass? 

Currently, I am using the NVIDIA V100 GPU with 16GB. I have also tested it with V100 32GB memory and still face the same issue. 

If more memory is required, do you plan on enabling unified memory in lingvo as I don't see that currently enabled?

**Comment by jonathanasdf** [comment]
Bazel by default tries to run multiple tests at once which can cause GPU OOM. This is a known issue. See eg. https://stackoverflow.com/questions/35090591/is-there-a-way-to-force-bazel-to-run-tests-serially

**Comment by msharmavikram** [comment]
Thanks for the information. It helped.
