### ISSUE TITLE
Usage of GPU in lingvo

### ISSUE THREAD

**Issue by msharmavikram** [tensorflow/lingvo#90]
Although I am trying to run GPipe (https://github.com/tensorflow/lingvo/issues/88), I wanted to understand some additional details on the lingvo/trainer command line parameters. I have two specific questions: 

1. Can you please provide some additional details on the following parameters? (this may be a dump question)

`--controller_gpus: Number of controller GPUs - default is 0`. What exactly this represent? From the format - it seems like how many GPUs are used for control purpose. Setting it to `0`, means there is no controller GPU or GPU 0 is by default acting as controller GPU?  

2. If I wanted to use only 1 GPU, instead of multiple GPU for testing purpose (scalability evaluation), how should I pass the parameters for the following parameters: (is the below one correct?)

`--controller_gpus=1`, `--worker_gpus=1` and `--worker_split_size=1`

**Comment by jonathanasdf** [comment]
Yes, controller_gpus is the number of gpus used for the controller. The controller is in charge of generating summaries and writing checkpoints, so in general it does not need to use a gpu so we leave it as 0.

If you want to only use 1 gpu for training, pass --worker_gpus=1. worker_split_size should default to 1 anyways.

**Comment by msharmavikram** [comment]
Thanks for details.
