### ISSUE TITLE
Have you finished BeamSearchDecode in ASR task?

### ISSUE THREAD

**Issue by iamxiaoyubei** [tensorflow/lingvo#91]
Hello,

I found that you have called `BeamSearchDecode` in `_InferenceSubgraph_Default`(*/lingvo/tasks/asr/model.py*). Then I found, in function `BeamSearchDecode` of `AsrDecoderBase` Class(*lingvo/tasks/asr/decoder.py*), `beam_search.BeamSearchDecode` is called.

```
  def BeamSearchDecode(self, encoder_outputs, num_hyps_per_beam_override=0):
    """Performs beam-search based decoding.

    Args:
      encoder_outputs: a NestedMap computed by encoder.
      num_hyps_per_beam_override: If set to a value <= 0, this parameter is
        ignored. If set to a value > 0, then this value will be used to override
        p.num_hyps_per_beam.

    Returns:
      BeamSearchDecodeOutput, a namedtuple containing the decode results
    """
    return self.beam_search.BeamSearchDecode(
        self.theta, encoder_outputs, num_hyps_per_beam_override,
        self._InitBeamSearchStateCallback, self._PreBeamSearchStepCallback,
        self._PostBeamSearchStepCallback)
```
But, `beam_search` is not assigned a value in `BaseBeamSearchDecoder`(*/lingvo/core/base_decoder.py*). Besides,the function  `BeamSearchDecode` in `BaseBeamSearchDecoder` Class was also not implemented.

```
 def BeamSearchDecode(self, encoder_outputs):
    # pylint: disable=line-too-long
    """Performs beam search based decoding.

    Args:
      encoder_outputs: the outputs of the encoder.
    returns:
      `.BeamSearchDecodeOutput`, A namedtuple whose elements are tensors.
    """
    # pylint: enable=line-too-long
    raise NotImplementedError('Abstract method')
```

Could you mind tell me where your `BeamSearchDecode` is implemented?(In `BeamSearchHelper`???) At the same time, where did you inherit it?

Thank you~

**Comment by jonathanasdf** [comment]
https://github.com/tensorflow/lingvo/blob/85f5f3fc768f2671e1768dea86339888fd22ef76/lingvo/core/base_decoder.py#L72

https://github.com/tensorflow/lingvo/blob/85f5f3fc768f2671e1768dea86339888fd22ef76/lingvo/core/base_decoder.py#L86

https://github.com/tensorflow/lingvo/blob/85f5f3fc768f2671e1768dea86339888fd22ef76/lingvo/core/beam_search_helper.py#L318

**Comment by iamxiaoyubei** [comment]
Thank you~
