### ISSUE TITLE
Lingvo Gpipe run time query

### ISSUE THREAD

**Issue by msharmavikram** [tensorflow/lingvo#92]
I was able to run lingvo + GPipe without any error using below command (4GPU in a node configuration):

```bazel-bin/lingvo/trainer --config=cuda --enable_asserts=false --run_locally=gpu --mode=sync --model=lm.one_billion_wds.OneBWdsGPipeTransformer --logdir=/tmp/mnist/log --logtostderr --controller_gpus=4 --worker_gpus=4 --worker_split_size=4```

Now, I am wondering, how do I figure out if it is actually doing it correctly!  Is there a way to see if the GPipe is splitting the layers across the devices ? Are there any logs the model posts? What should I look at?

**Comment by bignamehyp** [comment]
Yes, you should be able to find weight assignment information in the logs. For example, look for py_utils.py:1293

**Comment by msharmavikram** [comment]
You mean _LogPlacement() ? 
from here https://github.com/tensorflow/lingvo/blob/master/lingvo/core/py_utils.py#L1293

I will look into it. (I only see `=== worker 0 ===` in the log. This raised me to question how exactly gpipe works).
