### ISSUE TITLE
Autoregressive Transformer Model

### ISSUE THREAD

**Issue by agemagician** [tensorflow/lingvo#93]
Hello,

First, I want to thank you for the great framework.

Second, the current implementation of transformer model uses non-autoregressive, correct ?
If I want to switch to autoregressive transformer, what I need to modify in the framework to make it work ?

**Comment by orhanf** [comment]
hi, thank you for your interest. 
the current implementation is a vanilla Transformer, and it is autoregressive by default. 
unfortunately we don't have a non-autoregressive Transformer yet under Lingvo.

**Comment by agemagician** [comment]
This is actually perfect for me, because unfortunately, tensor2tensor library only support non-autoregressive in training and only support both during evaluation.

**Comment by agemagician** [comment]
Just to double confirm you don't use the target output shifted as an input to the decoder. You only use the output of the decoder as input to the decoder in the next step, correct ?

**Comment by orhanf** [comment]
correct

**Comment by agemagician** [comment]
Great, thanks a lot for the quick response :)
