### ISSUE TITLE
Multitask training tutorial

### ISSUE THREAD

**Issue by agemagician** [tensorflow/lingvo#95]
Hello,

I am interested in multi-task training, like tensor2tensor.
I have checked that you have multi-task model, but I couldn't find any tutorial how to do it.

In my case, I am interesting to have something like:
1. Task 1: Language Modelling.
2. Task 2: Translation.
3. Task 3: Classification

**Comment by jonathanasdf** [comment]
There is a small section in the paper https://arxiv.org/pdf/1902.08295.pdf

We don't have any public examples or tutorials for it right now, sorry.

**Comment by agemagician** [comment]
Thanks for the reply.
Hopefully, you can make a public example soon.
