### ISSUE TITLE
Error when building with bazel

### ISSUE THREAD

**Issue by by2101** [tensorflow/lingvo#99]
Dear all,

I am trying to compile lingvo with bazel. My enviroment:
gcc 4.8.5
cuda 9.0
tensorflow-gpu       1.13.0rc0
tf-nightly           1.14.1.dev20190603

And I encountered following error:

`(py2) [user@localhost lingvo]$ bazel build -c opt //lingvo:trainer
Starting local Bazel server and connecting to it...
INFO: Analysed target //lingvo:trainer (37 packages loaded, 4755 targets configured).
INFO: Found 1 target...
ERROR: /home/user/lingvo/lingvo/core/ops/BUILD:216:1: C++ compilation of rule '//lingvo/core/ops:functional_ops_kernels' failed (Exit1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 90 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
lingvo/core/ops/functional_ops_kernels.cc: In function 'void tensorflow::lingvo::{anonymous}::SetRunOptions(tensorflow::OpKernelContext*, tensorflow::FunctionLibraryRuntime::Options*, bool)':
lingvo/core/ops/functional_ops_kernels.cc:33:17: error: assignment of read-only member 'tensorflow::FunctionLibraryRuntime::Options::step_id'
   opts->step_id = ctx->step_id();
                 ^
Target //lingvo:trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 22.332s, Critical Path: 18.42s
INFO: 18 processes: 18 processwrapper-sandbox.
FAILED: Build did NOT complete successfully`

How to solve this? Thank you!

**Comment by by2101** [comment]
Solved when I update the code.

**Comment by Singed-jj** [comment]
What kind of code did you update?

**Comment by ramonsanabria** [comment]
hi, I am facing the same issue. Any advice on this?

**Comment by Singed-jj** [comment]
I updated in dev.dockerfile
>RUN pip3 --no-cache-dir install tensorflow-gpu
To
>RUN pip3 --no-cache-dir install tensorflow-gpu==2.1.0
because of "waymo-open-dataset-tf-2-1-0"
and it solved the problem.

**Comment by ramonsanabria** [comment]
ok thanks!
